[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
opacity = 0.80
blur = true
title = ""

[font]
# normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 12
offset.y = -2 # for screen 2560 x 1600

[general]
# Configurations here
# https://alacritty.org/config-alacritty.html

live_config_reload = false
