# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

# Global properties
separator=true
separator_block_width=15

#[rofi-wttr]
#command=/home/gresces/.config/script/i3blocks/rofi-wttr
#interval=3600
#BAR_POSITION=top
#FONT=Monospace 10
#LABEL=
#LOCATION=Jincheng
#ROFI_CONFIG_FILE=/dev/null

# Guess the weather hourly
#[weather]
#command=curl -Ss 'http://wttr.in/Jincheng?format=%C+%t(%f)'
#interval=3600
#color=#A4C2F4

# Query my default IP address only on startup
[wifi]
command=nmcli | awk '/wlo1/&&/connected to/ {print $4}'
interval=once
color=#fff

#[ip]
#command=ip a | awk '/wlo1/ && /inet/{print $2}' | awk -F "/" '{print $1}' 
#interval=once
#color=#fff

[battery-poly]
command=/home/gresces/.config/script/i3blocks/battery-poly
LABEL=BAT
markup=pango
interval=5

[arch-update]
command=/home/gresces/.config/script/i3blocks/arch-update
interval=3600
markup=pango

[rofi-calendar]
command=/home/gresces/.config/script/i3blocks/rofi-calendar
interval=3600
BAR_POSITION=top
WEEK_START=monday
DATEFTM=+%Y-%m-%d
#SHORTFMT=+%d/%m/%Y
#LABEL=
FONT=Monospace 15
LEFTCLICK_PREV_MONTH=true
PREV_MONTH_TEXT= previous month 
NEXT_MONTH_TEXT= next month 
ROFI_CONFIG_FILE=/dev/null

# Update time every 5 seconds
[time]
command=date '+%H:%M:%S'
interval=1
